# Partir d'une image Python 3.9
FROM apache/airflow:2.8.1-python3.9

# Passer en root pour pouvoir installer des paquets système
USER root

# Installer les paquets système nécessaires pour scikit-surprise
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    build-essential \
    python3-dev \
    libpython3-dev \
    libatlas-base-dev \
    gcc \
    liblapack-dev \
    libblas-dev \
    gfortran && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Copier le fichier requirements.txt dans /tmp
COPY requirements.txt /tmp/requirements.txt

# Passer en airflow pour pouvoir installer les librairies
USER airflow

# Installer les dépendances
RUN pip install --no-cache-dir -r /tmp/requirements.txt
RUN pip install --no-cache-dir --upgrade "protobuf==4.21.12"

# Copier le code source de l'application
COPY ./src /opt/airflow/src

# Purger les paquets de build pour réduire la taille de l'image (optionnel) en passant d'un utilisateur à l'autre
USER root
RUN apt-get purge -y \
    build-essential \
    python3-dev \
    libpython3-dev \
    gcc && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*
USER airflow