FROM apache/airflow:2.8.1-python3.9
USER root
# Installer des outils supplémentaires pour pouvoir faire tourner scikit-surprise
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    build-essential \
    python3-dev \
    libpython3-dev \
    libatlas-base-dev \
    gcc \
    liblapack-dev \
    libblas-dev \
    gfortran && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*
COPY requirements.txt /tmp/requirements.txt
USER airflow
RUN pip install --no-cache-dir -r /tmp/requirements.txt

# Nettoyer pour réduire la taille de l'image (optionnel)
USER root
RUN apt-get purge -y \
    build-essential \
    python3-dev \
    libpython3-dev \
    gcc && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*
USER airflow
